### ISSUE TITLE
Spawner

### ISSUE THREAD

**Issue by MadooxMc** [CLADevs/VanillaX#88] opened 2021-08-11 22:47 UTC
What the multiworld that you use please, i am teleporter into the nether good but crash just after, (before i crash directly when i tp into nether)

error

PocketMine-MP Crash Dump Thu Aug 12 00:43:40 CEST 2021

Error: Expected a tag of type pocketmine\nbt\tag\IntTag, got pocketmine\nbt\tag\ShortTag
File: pmsrc/vendor/pocketmine/nbt/src/tag/CompoundTag
Line: 100
Type: RuntimeException

A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: VanillaX v2.1.0

Code:
[91] 	 * @phpstan-param class-string<T> $expectedClass
[92] 	 *
[93] 	 * @phpstan-return T|null
[94] 	 * @throws \RuntimeException if the tag exists and is not of the expected type (if specified)
[95] 	 */
[96] 	public function getTag(string $name, string $expectedClass = NamedTag::class) : ?NamedTag{
[97] 		assert(is_a($expectedClass, NamedTag::class, true));
[98] 		$tag = $this->value[$name] ?? null;
[99] 		if($tag !== null and !($tag instanceof $expectedClass)){
[100] 			throw new \RuntimeException("Expected a tag of type $expectedClass, got " . get_class($tag));
[101] 		}
[102] 
[103] 		return $tag;
[104] 	}
[105] 
[106] 	/**
[107] 	 * Returns the ListTag with the specified name, or null if it does not exist. Triggers an exception if a tag exists
[108] 	 * with that name and the tag is not a ListTag.
[109] 	 */
[110] 	public function getListTag(string $name) : ?ListTag{

**Comment by xXNiceYT** [comment] 2021-08-11 22:51
https://poggit.pmmp.io/r/134904/MultiWorld_dev-210.phar this is what i've used

**Comment by xXNiceYT** [comment] 2021-08-11 22:51
that error suppose to only occur when gamerule is on in config h, can you send console error rather than crashdump?

**Comment by MadooxMc** [comment] 2021-08-11 22:58
When i am connected, before , i crash directly, now i am connected in nether and i can go in normal world but in the end, i habe crash directly and when i test to connected another , server crash directly, the console error is that: 

Done (0.885s)! For help, type "help" or "?"
2021-08-12 [00:54:21] [Server thread/INFO]: Mlaskar[/176.167.196.165:56703] logged in with entity id 2 at (end2, 152.9783, 48, 379.7948)
2021-08-12 [00:54:22] [Server thread/CRITICAL]: RuntimeException: "Expected a tag of type pocketmine\nbt\tag\IntTag, got pocketmine\nbt\tag\ShortTag" (EXCEPTION) in "pmsrc/vendor/pocketmine/nbt/src/tag/CompoundTag" at line 100
2021-08-12 [00:54:22] [Server thread/CRITICAL]: #0 pmsrc/vendor/pocketmine/nbt/src/tag/CompoundTag(170): pocketmine\nbt\tag\CompoundTag->getTag(string[10] SpawnCount, string[25] pocketmine\nbt\tag\IntTag)
2021-08-12 [00:54:22] [Server thread/CRITICAL]: #1 pmsrc/vendor/pocketmine/nbt/src/tag/CompoundTag(195): pocketmine\nbt\tag\CompoundTag->getTagValue(string[10] SpawnCount, string[25] pocketmine\nbt\tag\IntTag, NULL , boolean )
2021-08-12 [00:54:22] [Server thread/CRITICAL]: #2 plugins/VanillaX_dev-107.phar/src/CLADevs/VanillaX/blocks/tile/MobSpawnerTile(126): pocketmine\nbt\tag\CompoundTag->getInt(string[10] SpawnCount)
2021-08-12 [00:54:22] [Server thread/CRITICAL]: #3 pmsrc/src/pocketmine/tile/Tile(167): CLADevs\VanillaX\blocks\tile\MobSpawnerTile->readSaveData(object pocketmine\nbt\tag\CompoundTag)
2021-08-12 [00:54:22] [Server thread/CRITICAL]: #4 pmsrc/src/pocketmine/tile/Spawnable(62): pocketmine\tile\Tile->__construct(object pocketmine\level\Level, object pocketmine\nbt\tag\CompoundTag)
2021-08-12 [00:54:22] [Server thread/CRITICAL]: #5 pmsrc/src/pocketmine/tile/Tile(116): pocketmine\tile\Spawnable->__construct(object pocketmine\level\Level, object pocketmine\nbt\tag\CompoundTag)
2021-08-12 [00:54:22] [Server thread/CRITICAL]: #6 pmsrc/src/pocketmine/level/format/Chunk(723): pocketmine\tile\Tile::createTile(string[10] MobSpawner, object pocketmine\level\Level, object pocketmine\nbt\tag\CompoundTag)
2021-08-12 [00:54:22] [Server thread/CRITICAL]: #7 pmsrc/src/pocketmine/level/Level(2683): pocketmine\level\format\Chunk->initChunk(object pocketmine\level\Level)
2021-08-12 [00:54:22] [Server thread/CRITICAL]: #8 pmsrc/src/pocketmine/level/Level(2295): pocketmine\level\Level->loadChunk(integer 10, integer 23, boolean 1)
2021-08-12 [00:54:22] [Server thread/CRITICAL]: #9 pmsrc/src/pocketmine/level/Level(2957): pocketmine\level\Level->getChunk(integer 10, integer 23, boolean 1)
2021-08-12 [00:54:22] [Server thread/CRITICAL]: #10 pmsrc/src/pocketmine/Player(1061): pocketmine\level\Level->populateChunk(integer 10, integer 23)
2021-08-12 [00:54:22] [Server thread/CRITICAL]: #11 pmsrc/src/pocketmine/Player(1857): pocketmine\Player->sendNextChunk()
2021-08-12 [00:54:22] [Server thread/CRITICAL]: #12 pmsrc/src/pocketmine/Server(2399): pocketmine\Player->checkNetwork()
2021-08-12 [00:54:22] [Server thread/CRITICAL]: #13 pmsrc/src/pocketmine/Server(2152): pocketmine\Server->tick()
2021-08-12 [00:54:22] [Server thread/CRITICAL]: #14 pmsrc/src/pocketmine/Server(1992): pocketmine\Server->tickProcessor()
2021-08-12 [00:54:22] [Server thread/CRITICAL]: #15 pmsrc/src/pocketmine/Server(1586): pocketmine\Server->start()
2021-08-12 [00:54:22] [Server thread/CRITICAL]: #16 pmsrc/src/pocketmine/PocketMine(311): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[51] /home/gameserver/servers/serveur7/minecraftbedrock/, string[59] /home/gameserver/servers/serveur7/minecraftbedrock/plugins/)
2021-08-12 [00:54:22] [Server thread/CRITICAL]: #17 pmsrc/src/pocketmine/PocketMine(341): pocketmine\server()
2021-08-12 [00:54:22] [Server thread/CRITICAL]: #18 pmsrc(11): require(string[106] phar:///home/gameserver/servers/serveur7/minecraftbedrock/PocketMine-MP.phar/src)
2021-08-12 [00:54:22] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
2021-08-12 [00:54:22] [Server thread/EMERGENCY]: Please upload the "/home/gameserver/servers/serveur7/minecraftbedrock/crashdumps/Thu_Aug_12-00.54.22-CEST_2021.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
2021-08-12 [00:54:22] [Server thread/EMERGENCY]: The crash dump has been automatically submitted to the Crash Archive. You can view it on https://crash.pmmp.io/view/5104641 or use the ID #5104641.

**Comment by xXNiceYT** [comment] 2021-08-11 23:00
Ah that’s spawner not multi world, do you by chance have a spawner plugin? That overwrites VanillaX one?

**Comment by xXNiceYT** [comment] 2021-08-11 23:08
Replace this with
```#  #List of blocks that wont be registered
#  blocks:
#    - 145 #This would be anvil block Id
```
With
```  #List of blocks that wont be registered
  blocks:
    - 52 #spawner id
``` in Config should fix it

**Comment by MadooxMc** [comment] 2021-08-11 23:15
Yes i have spawner in my nether but he is functional and i dont know whats plugin do this?, ooh okkkk is the problem, i have spawner enderman into end to!! Thank you very mutch i will try that

**Comment by MadooxMc** [comment] 2021-08-11 23:39
You are the best ! And you plugin to! I don’t crash in Nether !!! I’m crashing in end but i think is not the more importent you have fix my crash on nether and keepinventory it was more important for me, Thank you!!!

**Comment by xXNiceYT** [comment] 2021-08-11 23:40
If end crash was caused by this plugin i can fix that

**Comment by MadooxMc** [comment] 2021-08-11 23:42
I think it’s spawner enderman, i send you console error

Mlaskar joined the game
2021-08-12 [01:37:54] [Server thread/CRITICAL]: RuntimeException: "Expected a tag of type pocketmine\nbt\tag\IntTag, got pocketmine\nbt\tag\ShortTag" (EXCEPTION) in "pmsrc/vendor/pocketmine/nbt/src/tag/CompoundTag" at line 100
2021-08-12 [01:37:54] [Server thread/CRITICAL]: #0 pmsrc/vendor/pocketmine/nbt/src/tag/CompoundTag(170): pocketmine\nbt\tag\CompoundTag->getTag(string[10] SpawnCount, string[25] pocketmine\nbt\tag\IntTag)
2021-08-12 [01:37:54] [Server thread/CRITICAL]: #1 pmsrc/vendor/pocketmine/nbt/src/tag/CompoundTag(195): pocketmine\nbt\tag\CompoundTag->getTagValue(string[10] SpawnCount, string[25] pocketmine\nbt\tag\IntTag, NULL , boolean )
2021-08-12 [01:37:54] [Server thread/CRITICAL]: #2 plugins/VanillaX_dev-107.phar/src/CLADevs/VanillaX/blocks/tile/MobSpawnerTile(126): pocketmine\nbt\tag\CompoundTag->getInt(string[10] SpawnCount)
2021-08-12 [01:37:54] [Server thread/CRITICAL]: #3 pmsrc/src/pocketmine/tile/Tile(167): CLADevs\VanillaX\blocks\tile\MobSpawnerTile->readSaveData(object pocketmine\nbt\tag\CompoundTag)
2021-08-12 [01:37:54] [Server thread/CRITICAL]: #4 pmsrc/src/pocketmine/tile/Spawnable(62): pocketmine\tile\Tile->__construct(object pocketmine\level\Level, object pocketmine\nbt\tag\CompoundTag)
2021-08-12 [01:37:54] [Server thread/CRITICAL]: #5 pmsrc/src/pocketmine/tile/Tile(116): pocketmine\tile\Spawnable->__construct(object pocketmine\level\Level, object pocketmine\nbt\tag\CompoundTag)
2021-08-12 [01:37:54] [Server thread/CRITICAL]: #6 pmsrc/src/pocketmine/level/format/Chunk(723): pocketmine\tile\Tile::createTile(string[10] MobSpawner, object pocketmine\level\Level, object pocketmine\nbt\tag\CompoundTag)
2021-08-12 [01:37:54] [Server thread/CRITICAL]: #7 pmsrc/src/pocketmine/level/Level(2683): pocketmine\level\format\Chunk->initChunk(object pocketmine\level\Level)
2021-08-12 [01:37:54] [Server thread/CRITICAL]: #8 pmsrc/src/pocketmine/level/Level(2295): pocketmine\level\Level->loadChunk(integer 8, integer 24, boolean )
2021-08-12 [01:37:54] [Server thread/CRITICAL]: #9 pmsrc/src/pocketmine/level/Level(2013): pocketmine\level\Level->getChunk(integer 8, integer 24)
2021-08-12 [01:37:54] [Server thread/CRITICAL]: #10 plugins/SlapperRotation.phar/src/SlapperRotation/Main(28): pocketmine\level\Level->getNearbyEntities(object pocketmine\math\AxisAlignedBB, object pocketmine\Player)
2021-08-12 [01:37:54] [Server thread/CRITICAL]: #11 pmsrc/src/pocketmine/plugin/MethodEventExecutor(42): SlapperRotation\Main->onPlayerMove(object pocketmine\event\player\PlayerMoveEvent)
2021-08-12 [01:37:54] [Server thread/CRITICAL]: #12 pmsrc/src/pocketmine/plugin/RegisteredListener(80): pocketmine\plugin\MethodEventExecutor->execute(object SlapperRotation\Main, object pocketmine\event\player\PlayerMoveEvent)
2021-08-12 [01:37:54] [Server thread/CRITICAL]: #13 pmsrc/src/pocketmine/event/Event(88): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\player\PlayerMoveEvent)
2021-08-12 [01:37:54] [Server thread/CRITICAL]: #14 pmsrc/src/pocketmine/Player(1663): pocketmine\event\Event->call()
2021-08-12 [01:37:54] [Server thread/CRITICAL]: #15 pmsrc/src/pocketmine/Player(1776): pocketmine\Player->processMostRecentMovements()
2021-08-12 [01:37:54] [Server thread/CRITICAL]: #16 pmsrc/src/pocketmine/level/Level(854): pocketmine\Player->onUpdate(integer 916)
2021-08-12 [01:37:54] [Server thread/CRITICAL]: #17 pmsrc/src/pocketmine/level/Level(787): pocketmine\level\Level->actuallyDoTick(integer 916)
2021-08-12 [01:37:54] [Server thread/CRITICAL]: #18 pmsrc/src/pocketmine/Server(2265): pocketmine\level\Level->doTick(integer 916)
2021-08-12 [01:37:54] [Server thread/CRITICAL]: #19 pmsrc/src/pocketmine/Server(2396): pocketmine\Server->checkTickUpdates(integer 916, double 1628725074.9104)
2021-08-12 [01:37:54] [Server thread/CRITICAL]: #20 pmsrc/src/pocketmine/Server(2152): pocketmine\Server->tick()
2021-08-12 [01:37:54] [Server thread/CRITICAL]: #21 pmsrc/src/pocketmine/Server(1992): pocketmine\Server->tickProcessor()
2021-08-12 [01:37:54] [Server thread/CRITICAL]: #22 pmsrc/src/pocketmine/Server(1586): pocketmine\Server->start()
2021-08-12 [01:37:54] [Server thread/CRITICAL]: #23 pmsrc/src/pocketmine/PocketMine(311): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[51] /home/gameserver/servers/serveur7/minecraftbedrock/, string[59] /home/gameserver/servers/serveur7/minecraftbedrock/plugins/)
2021-08-12 [01:37:54] [Server thread/CRITICAL]: #24 pmsrc/src/pocketmine/PocketMine(341): pocketmine\server()
2021-08-12 [01:37:54] [Server thread/CRITICAL]: #25 pmsrc(11): require(string[106] phar:///home/gameserver/servers/serveur7/minecraftbedrock/PocketMine-MP.phar/src)
2021-08-12 [01:37:54] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
2021-08-12 [01:37:54] [Server thread/EMERGENCY]: Please upload the "/home/gameserver/servers/serveur7/minecraftbedrock/crashdumps/Thu_Aug_12-01.37.54-CEST_2021.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
2021-08-12 [01:37:55] [Server thread/EMERGENCY]: The crash dump has been automatically submitted to the Crash Archive. You can view it on https://crash.pmmp.io/view/5104738 or use the ID #5104738.

Thank you for all

**Comment by xXNiceYT** [comment] 2021-08-11 23:44
O its the same error, it should be fixed by putting 52 in the config disabled blocks section the `#disabled:`  should be `disabled:` if it isnt

**Comment by MadooxMc** [comment] 2021-08-11 23:49
Ok thank you, but my mobs dont walk, he is imobil :(

**Comment by MadooxMc** [comment] 2021-08-11 23:52
I dont found disabled block :S

**Comment by xXNiceYT** [comment] 2021-08-11 23:55
Turn vanillax mobs off if you got pure entities

**Comment by xXNiceYT** [comment] 2021-08-11 23:55
mobs: false in Config

**Comment by MadooxMc** [comment] 2021-08-12 00:09
Thank you😍😍 what the better ? VannilaX mobs or pure entities mobs? And i have to the plugin Emote and the plugin VanillaInventory (is vanilla anvil and enchantment) is useless with VanillaX?

**Comment by MadooxMc** [comment] 2021-08-12 00:22
I have again the crash in end i think my -52 is bad, it’s good config?

---
#If this is false mobs will not register through VanillaX plugin
mobs: false

#Anything listed here, would not be registered from this plugin.
#If you would like all of these to be registered, delete the disabled section from the config.yml
#item. or you would want enchantments to be registered, but other to not be registered,
#simpily delete the enchantments section and you should be set.
disabled:
#  #Mobs includes armor stand, zombies, etc.
#  mobs:
#    - 43 #this would be blaze entity Id
#
#  #List of blocks that wont be registered
#  blocks:
     - 52 #spawner id
#
#  #Items includes Firework, Armor Stand and so on
#  items:
#    - 513 #This would be shield item Id
#
#  #Commands that wont be registered, they must be all lowercase.
#  commands:
#    - "gamerule"
#
#  #Enchantments that wont be register
#  enchantments:
#    - 25 #ID of the Frost Walker Enchantment

#Features you can disable
features:
  #Disables weather including /weather
  weather: false
  #Disables gamerule and removes command /gamerule
  gamerule: false

#if this is true and gamerule feature is off, it will delete previous game rule.
gamerule-remove-cache: true
...

**Comment by xXNiceYT** [comment] 2021-08-12 00:23
Pure Entities features entity that can actually move and has a ai which vanillax doesn’t so pure entities is better.

this plugin implements emote, anvil & enchantment inventories

**Comment by xXNiceYT** [comment] 2021-08-12 00:25
[config.zip](https://github.com/CLADevs/VanillaX/files/6972056/config.zip)
try using this config.yml its inside the zip, replace it with ur config.yml

**Comment by MadooxMc** [comment] 2021-08-12 00:39
I haven’t the word…. You are the best ! Thank you very mutch for you magic plugin 😍 is good with your config, no crash is just beautiful!!

**Comment by xXNiceYT** [comment] 2021-08-12 00:45
issue resolved?

**Comment by MadooxMc** [comment] 2021-08-12 01:04
Yes but i don’t understand, now firework and triddent do crash my server 😭

**Comment by xXNiceYT** [comment] 2021-08-12 01:05
Ah, its because mobs: false disables trident & firework which are entities, ill fix it  in bit

**Comment by MadooxMc** [comment] 2021-08-12 01:09
Aah ok thank you once again 😁

**Comment by xXNiceYT** [comment] 2021-08-12 01:18
Should be fixed on latest build

**Comment by MadooxMc** [comment] 2021-08-12 01:25
Ok 👌 😁

**Comment by MadooxMc** [comment] 2021-08-12 01:44
It’s goooooood 😁, my last problem would be that the brewing stand no longer works,
I can no longer place anything in it, earlier I could make potions but I had to take the water potions in creative because the glass bottle does not fill up when you click on the water

**Comment by xXNiceYT** [comment] 2021-08-12 01:48
seems to work fine for me

**Comment by MadooxMc** [comment] 2021-08-12 02:11
Work fine to after a restart ! 😁

**Comment by xXNiceYT** [comment] 2021-08-12 02:11
OKay

**Closed by xXNiceYT** 2021-08-12 02:11 UTC

**Comment by SPMP2** [comment] 2021-08-29 15:37
Spawner crashing my server but y use 
    - 52 //spawner id 
    in config

**Comment by xXNiceYT** [comment] 2021-08-29 15:38
Can’t help with no crash log

**Comment by SPMP2** [comment] 2021-08-29 15:40
2021-08-29 [17:35:30] [Server thread/CRITICAL]: RuntimeException: "Expected a tag of type pocketmine\nbt\tag\IntTag, got pocketmine\nbt\tag\ShortTag" (EXCEPTION) in "pmsrc/vendor/pocketmine/nbt/src/tag/CompoundTag" at line 100
--
314 | 2021-08-29 [17:35:30] [Server thread/CRITICAL]: #0 pmsrc/vendor/pocketmine/nbt/src/tag/CompoundTag(170): pocketmine\nbt\tag\CompoundTag->getTag(string[10] SpawnCount, string[25] pocketmine\nbt\tag\IntTag)
315 | 2021-08-29 [17:35:30] [Server thread/CRITICAL]: #1 pmsrc/vendor/pocketmine/nbt/src/tag/CompoundTag(195): pocketmine\nbt\tag\CompoundTag->getTagValue(string[10] SpawnCount, string[25] pocketmine\nbt\tag\IntTag, NULL , boolean )
316 | 2021-08-29 [17:35:30] [Server thread/CRITICAL]: #2 plugins/VanillaX_dev-112.phar/src/CLADevs/VanillaX/blocks/tile/MobSpawnerTile(126): pocketmine\nbt\tag\CompoundTag->getInt(string[10] SpawnCount)
317 | 2021-08-29 [17:35:30] [Server thread/CRITICAL]: #3 pmsrc/src/pocketmine/tile/Tile(167): CLADevs\VanillaX\blocks\tile\MobSpawnerTile->readSaveData(object pocketmine\nbt\tag\CompoundTag)
318 | 2021-08-29 [17:35:30] [Server thread/CRITICAL]: #4 pmsrc/src/pocketmine/tile/Spawnable(62): pocketmine\tile\Tile->__construct(object pocketmine\level\Level, object pocketmine\nbt\tag\CompoundTag)
319 | 2021-08-29 [17:35:30] [Server thread/CRITICAL]: #5 pmsrc/src/pocketmine/tile/Tile(116): pocketmine\tile\Spawnable->__construct(object pocketmine\level\Level, object pocketmine\nbt\tag\CompoundTag)
320 | 2021-08-29 [17:35:30] [Server thread/CRITICAL]: #6 pmsrc/src/pocketmine/level/format/Chunk(723): pocketmine\tile\Tile::createTile(string[10] MobSpawner, object pocketmine\level\Level, object pocketmine\nbt\tag\CompoundTag)
321 | 2021-08-29 [17:35:30] [Server thread/CRITICAL]: #7 pmsrc/src/pocketmine/level/Level(2683): pocketmine\level\format\Chunk->initChunk(object pocketmine\level\Level)
322 | 2021-08-29 [17:35:30] [Server thread/CRITICAL]: #8 pmsrc/src/pocketmine/level/Level(2295): pocketmine\level\Level->loadChunk(integer 15, integer 20, boolean 1)
323 | 2021-08-29 [17:35:30] [Server thread/CRITICAL]: #9 pmsrc/src/pocketmine/level/Level(2957): pocketmine\level\Level->getChunk(integer 15, integer 20, boolean 1)
324 | 2021-08-29 [17:35:30] [Server thread/CRITICAL]: #10 pmsrc/src/pocketmine/Player(1061): pocketmine\level\Level->populateChunk(integer 15, integer 20)
325 | 2021-08-29 [17:35:30] [Server thread/CRITICAL]: #11 pmsrc/src/pocketmine/Player(1857): pocketmine\Player->sendNextChunk()
326 | 2021-08-29 [17:35:30] [Server thread/CRITICAL]: #12 pmsrc/src/pocketmine/Server(2399): pocketmine\Player->checkNetwork()
327 | 2021-08-29 [17:35:30] [Server thread/CRITICAL]: #13 pmsrc/src/pocketmine/Server(2152): pocketmine\Server->tick()
328 | 2021-08-29 [17:35:30] [Server thread/CRITICAL]: #14 pmsrc/src/pocketmine/Server(1992): pocketmine\Server->tickProcessor()
329 | 2021-08-29 [17:35:30] [Server thread/CRITICAL]: #15 pmsrc/src/pocketmine/Server(1586): pocketmine\Server->start()
330 | 2021-08-29 [17:35:30] [Server thread/CRITICAL]: #16 pmsrc/src/pocketmine/PocketMine(314): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[51] /home/gameserver/servers/serveur7/minecraftbedrock/, string[59] /home/gameserver/servers/serveur7/minecraftbedrock/plugins/)
331 | 2021-08-29 [17:35:30] [Server thread/CRITICAL]: #17 pmsrc/src/pocketmine/PocketMine(344): pocketmine\server()
332 | 2021-08-29 [17:35:30] [Server thread/CRITICAL]: #18 pmsrc(11): require(string[106] phar:///home/gameserver/servers/serveur7/minecraftbedrock/PocketMine-MP.phar/src)
333 | 2021-08-29 [17:35:30] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
334 | 2021-08-29 [17:35:30] [Server thread/EMERGENCY]: Please upload the "/home/gameserver/servers/serveur7/minecraftbedrock/crashdumps/Sun_Aug_29-17.35.30-CEST_2021.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.

**Comment by xXNiceYT** [comment] 2021-08-29 15:41
VanillaX & other spawner aren’t compatible so turn vanillax spawner on then destroy the spawner then disable spawner again once you destroy spawner in the qorld

**Comment by SPMP2** [comment] 2021-08-29 15:44
Ok thank’s !!
