### ISSUE TITLE
VanillaX doesn't validate InventoryTransactionPacket

### ISSUE THREAD

**Issue by ipad54** [CLADevs/VanillaX#135] opened 2021-12-08 11:40 UTC
https://youtu.be/sPpmsabqSnc

PM4

**Comment by xXNiceYT** [comment] 2021-12-08 20:55
Thank you I was looking forward to this. I could not test it myself because I didn’t had any hack clients now it’s confirmed, that fake items works I’ll fix it

**Comment by ipad54** [comment] 2021-12-09 05:28
You can download Toolbox on your phone

**Comment by xXNiceYT** [comment] 2021-12-09 11:46
Yeah, but I don’t got any androids. I mostly use my pc for gaming, and downloading those hacks might have virus so I just try not to get them unless it’s horion which I can compile it myself

**Comment by ipad54** [comment] 2021-12-09 11:49
Try https://github.com/disepi/ambrosial

**Comment by xXNiceYT** [comment] 2021-12-09 11:55
Thanks, does it have give command which gives fake item? Or duper like how horion had

**Comment by ipad54** [comment] 2021-12-09 11:59
.give

**Comment by xXNiceYT** [comment] 2022-01-22 18:20
@ipad54 this might be fixed in 4.0 by dylan i cant do .give and keep item given to me by the hack client

**Comment by ipad54** [comment] 2022-01-22 18:27
A hacker can send an InventoryTransactionPacket directly to the trading inventory

**Comment by xXNiceYT** [comment] 2022-01-22 19:01
true ill check on that

**Closed as completed** 2022-01-29 15:56 UTC
